In [1]:
!pip install transformers

     |████████████████████████████████| 3.8 MB 5.4 MB/s 
     |████████████████████████████████| 895 kB 53.1 MB/s 
     |████████████████████████████████| 67 kB 4.2 MB/s 
     |████████████████████████████████| 6.5 MB 35.5 MB/s 
     |████████████████████████████████| 596 kB 39.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
import tensorflow as tf
from transformers import TFAutoModelForCausalLM, AutoTokenizer

In [3]:
tokenizer = AutoTokenizer.from_pretrained("xlnet-base-cased")

Downloading:   0%|          | 0.00/760 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/779k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.32M [00:00<?, ?B/s]

In [12]:
model = TFAutoModelForCausalLM.from_pretrained("xlnet-base-cased")

Downloading:   0%|          | 0.00/539M [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFXLNetLMHeadModel.

All the layers of TFXLNetLMHeadModel were initialized from the model checkpoint at xlnet-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFXLNetLMHeadModel for predictions without further training.


In [4]:
tokenizer.vocab_size

32000

In [5]:
vocab = tokenizer.get_vocab()
vocab

{'Base': 26866,
 'NAM': 28452,
 '▁questioned': 6242,
 '▁article': 1447,
 'SIA': 23115,
 '▁Wei': 7837,
 '▁consciousness': 9093,
 '▁11,000': 23141,
 'aries': 6873,
 '▁organization': 1239,
 '▁preserving': 17305,
 'technical': 25891,
 'pedia': 27123,
 '▁diarrhea': 21144,
 '▁platter': 28539,
 '▁Irene': 24410,
 'ional': 11975,
 '▁ignoring': 13209,
 '▁connections': 6422,
 'excellent': 30168,
 '▁Chihuahua': 31972,
 '▁bristle': 27816,
 '▁TV': 1153,
 '▁severely': 9021,
 'PH': 10668,
 'rem': 14729,
 '▁Ul': 13490,
 '▁contender': 17699,
 '▁Cruz': 10201,
 '▁sacred': 10475,
 '▁canyon': 19020,
 '▁airspace': 21625,
 '▁Nikola': 20822,
 '▁Deputies': 28551,
 '▁Lawmakers': 26890,
 '▁Faso': 26412,
 'estrogen': 21303,
 '▁Circus': 27677,
 'width': 29750,
 '▁crop': 7308,
 '▁enforce': 9178,
 '▁kiosk': 29036,
 '▁forbid': 17663,
 '▁SR': 11851,
 '▁NATO': 2178,
 '▁gray': 6097,
 '▁pleased': 4972,
 '▁Dou': 20688,
 '▁36': 3248,
 'idad': 21410,
 '▁strength': 2280,
 '▁Hussein': 4770,
 '▁ineffective': 19640,
 '▁Zaragoza'

In [6]:
id2word = {i: word for word, i in vocab.items()}
id2word

{26866: 'Base',
 28452: 'NAM',
 6242: '▁questioned',
 1447: '▁article',
 23115: 'SIA',
 7837: '▁Wei',
 9093: '▁consciousness',
 23141: '▁11,000',
 6873: 'aries',
 1239: '▁organization',
 17305: '▁preserving',
 25891: 'technical',
 27123: 'pedia',
 21144: '▁diarrhea',
 28539: '▁platter',
 24410: '▁Irene',
 11975: 'ional',
 13209: '▁ignoring',
 6422: '▁connections',
 30168: 'excellent',
 31972: '▁Chihuahua',
 27816: '▁bristle',
 1153: '▁TV',
 9021: '▁severely',
 10668: 'PH',
 14729: 'rem',
 13490: '▁Ul',
 17699: '▁contender',
 10201: '▁Cruz',
 10475: '▁sacred',
 19020: '▁canyon',
 21625: '▁airspace',
 20822: '▁Nikola',
 28551: '▁Deputies',
 26890: '▁Lawmakers',
 26412: '▁Faso',
 21303: 'estrogen',
 27677: '▁Circus',
 29750: 'width',
 7308: '▁crop',
 9178: '▁enforce',
 29036: '▁kiosk',
 17663: '▁forbid',
 11851: '▁SR',
 2178: '▁NATO',
 6097: '▁gray',
 4972: '▁pleased',
 20688: '▁Dou',
 3248: '▁36',
 21410: 'idad',
 2280: '▁strength',
 4770: '▁Hussein',
 19640: '▁ineffective',
 29304: '▁Za

In [7]:
sequence = f"Once upon a time, there was "

In [9]:
input_ids = tokenizer.encode(sequence, return_tensors="tf")
input_ids

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[1977,  975,   24,   92,   19,  105,   30,    4,    3]],
      dtype=int32)>

In [10]:
id2word[1977]

'▁Once'

In [23]:
result = model(input_ids)

In [14]:
logits = result[0]
logits

<tf.Tensor: shape=(1, 9, 32000), dtype=float32, numpy=
array([[[-20.825836, -34.659054, -34.448845, ..., -27.784607,
         -30.744429, -35.803764],
        [-22.204262, -37.775715, -37.351635, ..., -30.710457,
         -29.529596, -36.70909 ],
        [-25.660433, -41.250134, -40.929314, ..., -33.94702 ,
         -31.243877, -37.11475 ],
        ...,
        [-19.059767, -33.74292 , -33.51809 , ..., -25.464394,
         -26.77374 , -34.887245],
        [-16.845306, -33.21242 , -32.902588, ..., -25.412735,
         -25.436691, -33.20153 ],
        [-14.362128, -31.215874, -30.875036, ..., -23.443596,
         -22.542252, -30.336594]]], dtype=float32)>

In [15]:
logits.shape

TensorShape([1, 9, 32000])

In [26]:
next_token_logits = logits[:, -1, :]
next_token_logits

<tf.Tensor: shape=(1, 32000), dtype=float32, numpy=
array([[-14.362128, -31.215874, -30.875036, ..., -23.443596, -22.542252,
        -30.336594]], dtype=float32)>

In [17]:
next_token_logits.shape

TensorShape([1, 32000])

In [18]:
top = tf.math.top_k(next_token_logits,k=10)
top

TopKV2(values=<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-5.3782597, -5.52251  , -5.793335 , -5.8336916, -6.0592346,
        -6.4627533, -6.72562  , -7.0102677, -7.0140924, -7.0365696]],
      dtype=float32)>, indices=<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 49,  17,  19,  66,   9, 545,  24, 125,  30,  21]], dtype=int32)>)

In [20]:
top.indices

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[ 49,  17,  19,  66,   9, 545,  24, 125,  30,  21]], dtype=int32)>

In [21]:
for i in top.indices[0].numpy().tolist():
    print(id2word[i])

▁or
▁
,
d
.
▁ever
▁a
▁just
▁was
▁and
