In [1]:
print('hi')

hi


In [8]:
import numpy as np

In [10]:
np.array([1,4,2,5])

array([1, 4, 2, 5])

In [9]:
np.array([1,4,2.5,5]) # broad casting

array([1. , 4. , 2.5, 5. ])

In [11]:
np.array([1,4,2.5,5],dtype = 'int') # broad casting

array([1, 4, 2, 5])

In [12]:
np.array([1,4,'a',5])

array(['1', '4', 'a', '5'], dtype='<U11')

In [14]:
np.array([[1,4,2],[1,1,2],[1,4,3]])

array([[1, 4, 2],
       [1, 1, 2],
       [1, 4, 3]])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.zeros(10,dtype='str')

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [19]:
np.zeros([2,3],dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [20]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [25]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.random.random([3,4])

array([[0.86925386, 0.03036987, 0.63969069, 0.3789351 ],
       [0.95226072, 0.71163556, 0.9924526 , 0.57035102],
       [0.71965982, 0.95539465, 0.62624075, 0.51746129]])

In [29]:
np.random.normal(0,100,[3,4])

array([[ -16.28922434,  -29.35013318, -126.75648148,  -73.09899172],
       [ 163.27024514,  201.95687675,  -48.64170251,  165.4846954 ],
       [ -96.6312681 ,   88.49218422,   96.8676732 ,  -28.91917147]])

In [30]:
np.random.normal(0,1,[3,4])

array([[ 0.81814552, -0.85794447,  0.47537655, -0.70389724],
       [ 1.20927654, -0.54238475, -0.35145989, -0.46232821],
       [ 0.03134542,  0.31870996,  0.91963939, -0.14882082]])

In [31]:
np.random.randint(0,10,30)

array([2, 3, 4, 3, 1, 3, 1, 7, 8, 3, 2, 2, 2, 7, 6, 3, 2, 5, 1, 4, 0, 3,
       5, 2, 6, 0, 0, 9, 7, 2])

In [38]:
x = np.arange(1,10)
y = np.arange(11,20)

In [39]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
x+y


array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [45]:
x*y

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [44]:
x/y

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421])

In [47]:
np.abs(x-y)

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [48]:
np.exp2(x)

array([  2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [50]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [52]:
np.power(y,x)

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579], dtype=int32)

In [53]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [54]:
np.sum(x)

45

In [55]:
np.mean(x)

5.0

In [56]:
np.prod(x)

362880

In [57]:
np.argmax(x) # 최대값의 인덱스

8

In [59]:
x[np.argmax(x)]

9

In [64]:
import pandas as pd
dict_data = {'a':1,'b':2,'c':3}
sr = pd.Series(dict_data)
print(type(sr))
print(sr)

<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64


In [67]:
list_data = ['2019-01-02',3.14,'abc',100,True]
sr = pd.Series(list_data)
print(sr)
sr[0]


0    2019-01-02
1          3.14
2           abc
3           100
4          True
dtype: object


RangeIndex(start=0, stop=5, step=1)

In [69]:
type(sr)

pandas.core.series.Series

In [71]:
data = ('민수','2017-04-08','여',True)
sr = pd.Series(data,index = ['이름','생년월일','성별','학생여부'])

In [72]:
print(sr) 

이름              민수
생년월일    2017-04-08
성별               여
학생여부          True
dtype: object


In [74]:
print(sr['이름'])

민수


In [79]:
print(sr[[1,2]])
sr[3:5]

생년월일    2017-04-08
성별               여
dtype: object


학생여부    True
dtype: object

In [85]:
sr[2:3]

성별    여
dtype: object

In [87]:
sr[[2,3]]

성별         여
학생여부    True
dtype: object

In [78]:
print(sr[['생년월일','성별']])

생년월일    2017-04-08
성별               여
dtype: object


In [92]:
sr[:]

이름              민수
생년월일    2017-04-08
성별               여
학생여부          True
dtype: object

In [102]:
dict_data = {'A':[1,2,3],'B':[4,5,6]} # data column
df = pd.DataFrame(dict_data,index = ['A','B','C'],columns = ['A','b'])
print(type(df))
print(df)
print(df.index)
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
   A    b
A  1  NaN
B  2  NaN
C  3  NaN
Index(['A', 'B', 'C'], dtype='object')
Index(['A', 'b'], dtype='object')


In [103]:
import pandas as pd
df = pd.DataFrame([[15,'남','덕영중'],[17,'여','수리중']]
                  ,index=['준서','예은']
                  ,columns=['나이','성별','학교'])
print(df)
print(df.index)
print(df.columns)
df.rename(columns={'연령':'age','성별':'gender','학교':'school'},inplace=True)
# inplace True 경우, df에 바로 적용된다.
print(df)
df.rename(columns={'age':'나이','성별':'gender','학교':'school'},inplace=False)
# inplace False 경우, 변수에 할당하지 않으면 print만 된다.
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
Index(['준서', '예은'], dtype='object')
Index(['나이', '성별', '학교'], dtype='object')
    나이 gender school
준서  15      남    덕영중
예은  17      여    수리중
    나이 gender school
준서  15      남    덕영중
예은  17      여    수리중


In [ ]:
exam_data = {}
exam_data['수학'] = [90,80,70]
exam_data['영어'] = [98,85,95]
exam_data['음악'] = [85,95,100]
exam_data['체육'] = [100,90,90]
df = pd.DataFrame(exam_data,index=['서준','우현','인아'])
df2 = df.copy()
df2.drop('우현',axis=0,inplace=True)
df2
df3 = df.copy()
df3.drop(['우현','인아']) # defalt inplace false 확인후 true설정
df3.drop(['우현','인아'],inplace=True) # drop axis : default = 0
df3
df3.drop(['수학'],axis=0)
df3.drop(['수학'],axis=1) # axis=1 : drop column

In [ ]:
exam_data = {}
exam_data['수학'] = [90,80,70]
exam_data['영어'] = [98,85,95]
exam_data['음악'] = [85,95,100]
exam_data['체육'] = [100,90,90]
df = pd.DataFrame(exam_data,index=['서준','우현','인아'])
label1 = df.loc['서준']
position1 = df.iloc[0]
print(label1)
print(position1)

label2 = df.loc[['서준','우현']]
print(label2)
position2 = df.iloc[[0,1]] # 인덱스 컬럼 위치 고려
print(position2)

label3 = df.loc['서준':'우현']
print(label3)
position3 = df.iloc[0:1]
print(position3)

In [ ]:
exam_data = {}
exam_data['이름'] = ['서준','우현','인아']
exam_data['수학'] = [90,80,70]
exam_data['영어'] = [98,85,95]
exam_data['음악'] = [85,95,100]
exam_data['체육'] = [100,90,90]
df = pd.DataFrame(exam_data)
print(df)
math1 = df['수학']
print(math1)
type(math1)

eng1 = df.영어
print(eng1)
type(eng1)
type(df)

df.iloc[::2]
df.iloc[0:3:2]
df.iloc[::-1]

In [105]:
exam_data = {}
exam_data['이름'] = ['서준','우현','인아']
exam_data['수학'] = [90,80,70]
exam_data['영어'] = [98,85,95]
exam_data['음악'] = [85,95,100]
exam_data['체육'] = [100,90,90]
df = pd.DataFrame(exam_data)
df
df.set_index('이름',inplace=True)
df.loc['서준',['음악']] # index column 순
df.iloc[0,[1]]
df.loc['서준','음악':'체육']
df.iloc[0,2:]
df.iloc[0:2,0:2]
df.iloc[:,:]


수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  85   95   90
인아  70  95  100   90

In [107]:
exam_data = {}
exam_data['이름'] = ['서준','우현','인아']
exam_data['수학'] = [90,80,70]
exam_data['영어'] = [98,85,95]
exam_data['음악'] = [85,95,100]
exam_data['체육'] = [100,90,90]
df = pd.DataFrame(exam_data)
df['국어'] = 80
df

이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  85   95   90  80
2  인아  70  95  100   90  80

In [1]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
df = titanic.loc[:,['age','fare']]
print(df.head())
print(type(df))
df
df + 1 # 프린팅만되고, int형만 연산

df.tail()
addition = df + 10
subtraction = addition - df # 데이터 프레임과의 연산
subtraction
titanic.shape
titanic.head()
titanic.info() # 컬럼명,데이터갯수,데이터타입
titanic.describe() # 전체데이터의 기초 통계
titanic.count() # info에 포함된 정보
titanic['sex'].value_counts() # 해당컬럼의 값분포
titanic['fare'].mean() # median,max,min,std,corr -> describe 에 포함된 정보
titanic['fare'].plot

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), categor

In [2]:
titanic['fare'].plot